version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_app
    ports:
      - "9020:9020"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB_NAME=weather_data
      - MONGO_USER=local
      - MONGO_PASS=local
      - APP_PORT=9020
      - DATA_PATH=./src/app/data/wx_data
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: local
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
